INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'PERSONAJE_CREATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'PERSONAJE_READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'PERSONAJE_UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (4, 'PERSONAJE_DELETE');

INSERT INTO AUTHORITY(ID, NAME) VALUES (5, 'KEY_CREATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (6, 'KEY_READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (7, 'KEY_UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (8, 'KEY_DELETE');

INSERT INTO AUTHORITY(ID, NAME) VALUES (9, 'ROLE_PERSONAJE_READER');